import { useState } from "react";
import { Mail, Plus, ShieldCheck, UserRound, X } from "lucide-react";
import Layout from "../components/Layout";
import { useAuth } from "../context/RoleContext";

const inputClass = "w-full rounded-xl border border-[#DDD8CE] bg-[#FAF9F6] px-3.5 py-2.5 text-sm text-[#292925] outline-none transition placeholder:text-[#AAA59C] focus:border-[#AAA399] focus:bg-white focus:ring-2 focus:ring-[#DED8CC]/60";

function Team() {
  const { currentOrganization, organizationMembers, addTeamMember } = useAuth();
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [form, setForm] = useState({ name: "", email: "", password: "", role: "Developer" });
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const set = (key) => (event) => setForm((current) => ({ ...current, [key]: event.target.value }));
  const submit = (event) => {
    event.preventDefault(); setError(""); setSuccess("");
    if (!form.name.trim() || !form.email.trim() || !form.password || !form.role) return setError("All fields are required.");
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) return setError("Enter a valid email address.");
    if (form.password.length < 8) return setError("Password must be at least 8 characters.");
    try { addTeamMember(form); setForm({ name: "", email: "", password: "", role: "Developer" }); setSuccess("Team member added successfully."); setIsFormOpen(false); } catch (err) { setError(err.message); }
  };
  return <Layout><section className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-1 text-xs font-semibold uppercase tracking-[0.16em] text-[#99948B]">Workspace Administration</p><h1 className="text-2xl font-semibold tracking-tight text-[#22221F] sm:text-3xl">Team Members</h1><p className="mt-1.5 max-w-xl text-sm leading-6 text-[#77736B]">Manage the people who work on {currentOrganization?.name || "your workspace"}.</p></div><button onClick={() => { setIsFormOpen(true); setError(""); setSuccess(""); }} className="inline-flex w-fit items-center justify-center gap-2 rounded-xl bg-[#292925] px-4 py-2.5 text-sm font-medium text-white transition hover:bg-[#3A3934]"><Plus size={17} />Add Team Member</button></section>
    {success && <p className="mb-5 rounded-xl border border-[#D6E1D1] bg-[#E7EEE4] px-4 py-3 text-sm font-medium text-[#536A4A]">{success}</p>}
    <section className="overflow-hidden rounded-2xl border border-[#E2DED5] bg-white shadow-[0_1px_2px_rgba(0,0,0,0.03)]"><div className="border-b border-[#EBE7DF] px-5 py-5 sm:px-6"><div className="flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#EEE8DD] text-[#514E47]"><ShieldCheck size={19} /></div><div><h2 className="font-semibold text-[#292925]">Workspace members</h2><p className="mt-1 text-xs text-[#8C877E]">{organizationMembers.length} member{organizationMembers.length === 1 ? "" : "s"} in this organization</p></div></div></div><div className="divide-y divide-[#ECE8E0]">{organizationMembers.map((member) => <div key={member.id} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div className="flex min-w-0 items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[#292925] text-xs font-semibold text-white">{member.name.split(" ").filter(Boolean).slice(0, 2).map((part) => part[0]).join("").toUpperCase()}</div><div className="min-w-0"><p className="truncate text-sm font-semibold text-[#292925]">{member.name}</p><p className="truncate text-xs text-[#827E76]">{member.email}</p></div></div><span className="w-fit rounded-full bg-[#EEE8DD] px-2.5 py-1 text-xs font-semibold text-[#625E57]">{member.role}</span></div>)}</div></section>
    {isFormOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4 py-6" onMouseDown={(event) => { if (event.target === event.currentTarget) setIsFormOpen(false); }}><section className="w-full max-w-lg rounded-2xl border border-[#E2DED5] bg-white p-6 shadow-xl sm:p-7"><div className="flex items-start justify-between gap-4"><div><h2 className="text-xl font-semibold text-[#292925]">Add Team Member</h2><p className="mt-1 text-sm text-[#77736B]">Create a Developer or Tester account for this workspace.</p></div><button onClick={() => setIsFormOpen(false)} className="rounded-lg p-2 text-[#77736B] hover:bg-[#EEE8DD]" aria-label="Close"><X size={18} /></button></div><form onSubmit={submit} className="mt-6 space-y-4"><label className="block"><span className="mb-2 block text-sm font-semibold text-[#45423D]">Full Name</span><div className="relative"><UserRound size={16} className="absolute left-3.5 top-3.5 text-[#99948B]" /><input value={form.name} onChange={set("name")} className={`${inputClass} pl-10`} placeholder="Full name" /></div></label><label className="block"><span className="mb-2 block text-sm font-semibold text-[#45423D]">Email</span><div className="relative"><Mail size={16} className="absolute left-3.5 top-3.5 text-[#99948B]" /><input type="email" value={form.email} onChange={set("email")} className={`${inputClass} pl-10`} placeholder="member@company.com" /></div></label><label className="block"><span className="mb-2 block text-sm font-semibold text-[#45423D]">Temporary Password</span><input type="password" value={form.password} onChange={set("password")} className={inputClass} placeholder="At least 8 characters" /></label><label className="block"><span className="mb-2 block text-sm font-semibold text-[#45423D]">Role</span><select value={form.role} onChange={set("role")} className={inputClass}><option>Developer</option><option>Tester</option></select></label>{error && <p className="rounded-xl bg-[#F4E4E2] px-3.5 py-3 text-xs font-medium text-[#8B3D37]">{error}</p>}<button className="w-full rounded-xl bg-[#292925] px-4 py-3 text-sm font-semibold text-white transition hover:bg-[#3A3934]">Create Account</button></form></section></div>}
  </Layout>;
}

export default Team;
